-- OpsMind 数据库清空脚本
--
-- 按外键依赖逆序清空所有表，保留表结构。
-- 使用 TRUNCATE ... CASCADE 快速清理并重置自增序列。
--
-- 加载方式：
--   docker compose exec -T postgres psql -U opsmind -d opsmind < scripts/reset-db.sql

BEGIN;

-- 禁用外键检查以加速（依赖逆序已保证安全）
SET session_replication_role = 'replica';

TRUNCATE TABLE messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE audit_logs RESTART IDENTITY CASCADE;
TRUNCATE TABLE chat_messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE chat_sessions RESTART IDENTITY CASCADE;
TRUNCATE TABLE ticket_records RESTART IDENTITY CASCADE;
TRUNCATE TABLE tickets RESTART IDENTITY CASCADE;
TRUNCATE TABLE knowledge_chunks RESTART IDENTITY CASCADE;
TRUNCATE TABLE knowledge_articles RESTART IDENTITY CASCADE;
TRUNCATE TABLE knowledge_bases RESTART IDENTITY CASCADE;
TRUNCATE TABLE llm_configs RESTART IDENTITY CASCADE;
TRUNCATE TABLE role_menus RESTART IDENTITY CASCADE;
TRUNCATE TABLE user_roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE menus RESTART IDENTITY CASCADE;
TRUNCATE TABLE users RESTART IDENTITY CASCADE;
TRUNCATE TABLE roles RESTART IDENTITY CASCADE;
TRUNCATE TABLE system_configs RESTART IDENTITY CASCADE;

-- 恢复外键检查
SET session_replication_role = 'origin';

COMMIT;
