-- OpsMind M1 回滚脚本
BEGIN;

DROP TABLE IF EXISTS sys_file CASCADE;
DROP TABLE IF EXISTS sys_config CASCADE;
DROP TABLE IF EXISTS knowledge_candidate CASCADE;
DROP TABLE IF EXISTS knowledge_sync_record CASCADE;
DROP TABLE IF EXISTS knowledge_review_record CASCADE;
DROP TABLE IF EXISTS knowledge_chunk CASCADE;
DROP TABLE IF EXISTS knowledge_article CASCADE;
DROP TABLE IF EXISTS knowledge_category CASCADE;
DROP TABLE IF EXISTS knowledge_base CASCADE;
DROP TABLE IF EXISTS ticket_visit_record CASCADE;
DROP TABLE IF EXISTS ticket_process_record CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS portal_chat_feedback CASCADE;
DROP TABLE IF EXISTS portal_chat_message CASCADE;
DROP TABLE IF EXISTS portal_chat_session CASCADE;
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS sys_operation_log CASCADE;
DROP TABLE IF EXISTS sys_login_log CASCADE;
DROP TABLE IF EXISTS sys_role_permission CASCADE;
DROP TABLE IF EXISTS sys_user_role CASCADE;
DROP TABLE IF EXISTS sys_permission CASCADE;
DROP TABLE IF EXISTS sys_role CASCADE;
DROP TABLE IF EXISTS sys_user CASCADE;

DROP EXTENSION IF EXISTS vector;

COMMIT;
